### ISSUE TITLE
MyBrain should follow the custom font 

### ISSUE THREAD

**Issue by aswedaw** [mhss1/MyBrain#1]
MyBrain should detect and follow the customized font of Android devices.
Currently, it doesn't. So, Myanmar Unicode went wrong on Xiaomi phones
with NotoSans Myanmar Zawdecode font as factory default. We have to customize the the font as Zawdecode is non-Unicode font. Thank you.

**Comment by mhss1** [comment]
Thank you for your feedback. I will make sure to fix this as soon as possible 👍
