### ISSUE TITLE
[Bug] App Crash When Clicking Some Calender Event On Dashboard

### ISSUE THREAD

**Issue by atikattar1104** [mhss1/MyBrain#103]
**Describe the bug**
App Crash When Clicking Any Calender Event On Dashboard.

**To Reproduce**
1. Go To Dashboard
2. Click On Any Calender Event
3. See App Crash

**Expected behavior**
Must Display Event As Usual.

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 10
 - App Version: 1.0.3
 - MIUI Version: 12.5

**Comment by mhss1** [comment]
Are these event added using "My Brain" app?

**Comment by mhss1** [comment]
Does the Location or any other field contains a URL?

**Comment by atikattar1104** [comment]
When Clicking Events Previously Created On Other Calenders (Like Outlook, Etc.), App Crashes. But, When Clicking Events Assigned To Other Calenders BUT Created In MyBrain, App Works As Usual.

**Comment by atikattar1104** [comment]
> Does the Location or any other field contains a URL?

Description Contains Some Sort Of Webpage Code. It Looks Like This :- 
![Screenshot_2022-10-28-22-14-16-806_com mhss app mybrain](https://user-images.githubusercontent.com/93785261/198689824-62ccd173-e737-4b28-9a4e-bdce52684bfd.jpg)

This Data Is Automatically Captured Using Calender Permission.

**Comment by atikattar1104** [comment]
Actually, Some Events Are Opening. Some Are Not.

**Comment by mhss1** [comment]
Fixed
