### ISSUE TITLE
Trying to Export Data Leads to Permissions

### ISSUE THREAD

**Issue by Temmie19** [mhss1/MyBrain#109]
**Expected Behaviour**
When going and clicking Export in the import/export data section after giving the app file storage permissions, the app lets you export the data probably as a file to a specified folder.

**Actual Behaviour**
Clicking on the Export button brings you back to the system settings of the app, rather than opening files. As if it was still trying to get permissions despite it not needing them. Also tried closing and force stopping the app to try to get different responses.

**To Reproduce**
1. Enter the app and go to the settings page
2. Select "Import data"
3. Select Export after giving the app file storage permissions

**Smartphone Specifications:**
 - Device: LG Nexus 5X
 - OS: Android 8.0.1
 - App Version: 1.0.3

**Comment by mhss1** [comment]
In step 2, did you mean "Export data"?

**Comment by Temmie19** [comment]
No. It only says Import Data. THEN you click Export.
![Screenshot_20221031-133920](https://user-images.githubusercontent.com/7474105/199095855-dfb2d297-89fb-4f7c-bf92-8014fdd25988.png)
![Screenshot_20221031-133948](https://user-images.githubusercontent.com/7474105/199096348-18c3a696-b5dc-44fc-a7af-10cbeea98e05.png)

**Comment by Temmie19** [comment]
I was actually going to do a PR soon to fix that minor bug so it says something along the lines of "Import/Export Data"

**Comment by mhss1** [comment]
I fixed it👍 but another problem happens when exporting with devices older than Android 9. I'll try to fix it and publish a release tomorrow to fix this and other issues happened in the last version.
