### ISSUE TITLE
Share to MyBrain Notes

### ISSUE THREAD

**Issue by paulz1** [mhss1/MyBrain#117]
**Is your feature request related to a problem? Please describe.**
When I select some text in another application (for example a browser) and click **Share** I have a proposition to share it for "MyBrain link" or "MyBrain link" or "MyBrain Tasks". It could be very usefull to be able to share also to "MyBrain Notes" (and may beeven "MyBrain Diary").

**Describe the solution you'd like**
I'd like to share some text from another app to MyBrain Notes using Share button.

**Comment by mhss1** [comment]
Added
