### ISSUE TITLE
[Feature Request] Add Ordering of Tasks by Due Date

### ISSUE THREAD

**Issue by transpersonify** [mhss1/MyBrain#118]
With other to-do app widgets, I like to see what's due on a particular day. I like MyBrain for all the other features, and so it would be nice to have a to-do list sorted by the **due date**, in order to see everyday tasks in one place.

What I want to happen: 
Go to Tasks -> Click on top left settings icon -> Ordered by ->
Add an option: "Date Due" ->  Ascending order.

This should reflect into the most urgent tasks first (this is different from the most important tasks, which are labelled by **priority** tab).

By default, this ordering is shown in the widgets, so that should take care of the daily tasks on the widget part.

**Comment by transpersonify** [comment]
Does this feature already exist? or did you commit changes ?

**Comment by mhss1** [comment]
I added the feature and it will be available in the next update
