### ISSUE TITLE
App crashes if there isn't a calendar app installed.

### ISSUE THREAD

**Issue by Rafee-M** [mhss1/MyBrain#124]
**Describe the bug**
When there isn't a calendar app present, the app crashes. 

**To Reproduce**
1. Don't have any calendar app installed
2. Click on Dashboard or Calendar in the app
3. Grant permission to access the calendar

**Expected behavior**
App won't crash and show calendar events.

**Screenshots**

https://user-images.githubusercontent.com/69535896/202842790-214d0015-21d3-4e02-90da-e3bef22f3aaa.mp4

**Smartphone (please complete the following information):**
 - Device: OnePlus 9RT
 - OS: Android 11
 - App Version 1.04

**Comment by mhss1** [comment]
Fixed
