### ISSUE TITLE
Caldendar doesn't show all calendars

### ISSUE THREAD

**Issue by ancientPrinter** [mhss1/MyBrain#13]
When adding calendars to show on the calendar section, only holidays and contact calendars from Google are shown. I got calendars from 4 accounts, with multiple calendars for each account.

1. Go to dashboard.
2. Grant calendar access.
3. Open the calendar space.
4. See error.

 - Device: Samsung Galaxy A32 4G
 - OS: Android 11
 - App Version: 1.0

I checked and unchecked every calendar for every account and, as I said, it seems like only holidays and contact calendars from Google are shown.

**Comment by mhss1** [comment]
Do you mean that the calendars appear but their events don't?

**Comment by ancientPrinter** [comment]
Yeah, the calendars appear, but their events don't.

**Comment by toshi2d** [comment]
Please fix

**Comment by mhss1** [comment]
Check out the latest release. I might fix your problem

**Comment by toshi2d** [comment]
Nope, latest realise (1.0.2) doesn't fix this bug :(

**Comment by mhss1** [comment]
I mean v1.0.3

**Comment by toshi2d** [comment]
Oh now it's fixed! Thank you!
