### ISSUE TITLE
Widget Issue

### ISSUE THREAD

**Issue by nileshrukhiyana60** [mhss1/MyBrain#134]
Facing issues with Widget
my mobile is Iqoo 9Se Android 13
![Screenshot_20221219_185442](https://user-images.githubusercontent.com/118615945/208436092-fb644b10-2342-48ab-9740-8bcf8b7940f1.jpg)

**Comment by mhss1** [comment]
Try restarting your phone

**Comment by nileshrukhiyana60** [comment]
> Try restarting your phone

Already did
