### ISSUE TITLE
Update notification icon/logo

### ISSUE THREAD

**Issue by tvnmguy** [mhss1/MyBrain#136]
![IMG_20230113_215556.jpg](https://user-images.githubusercontent.com/116799295/212369902-0d9ac111-c1e2-4dde-b054-4db6c5df1320.jpg)

Current notification logo invincible for me (MIUI 12.5.10 global) and suggesting to create new logo for notification purpose, like proposed above.

**Comment by mhss1** [comment]
Fixed
