### ISSUE TITLE
Squircle create button instead of circle button

### ISSUE THREAD

**Issue by tvnmguy** [mhss1/MyBrain#137]
![IMG_20230113_215102.jpg](https://user-images.githubusercontent.com/116799295/212371127-055cc587-7f97-444a-8ae2-26368fa685c1.jpg)

Replace current circle create button with little bit larger squircle button, I think which is more suitable considering the overall design of the app and larger size which make more accessible.

And also change the colour of  '+'  to dark when the squircle is lite and vice versa.

For example;

![IMG_20230113_220359.jpg](https://user-images.githubusercontent.com/116799295/212372432-d89442b2-3dd9-48e1-9a9b-0c3dc1455b02.jpg)

**Comment by ashway171** [comment]
Hey! really interested in collaborating. Could you please assign this issue to me !?
