### ISSUE TITLE
Defective Shadows Of Tiles In Notes!

### ISSUE THREAD

**Issue by atikattar1104** [mhss1/MyBrain#141]
**Describe the bug**
First Row (If Only 1-2 Notes Are Created) And Last Row (If More Than 2 Notes Are Created) Have Defective Shadows Of Tiles In Notes Section.
Other Upper Rows Doesn't Have Such Problem.
Also, After Deleting 2nd Note, 1st Notes Shadows Gets More Worse Than Before (See Last Screenshot. Can Be Fixed Using Reopening Notes Section, But Still, It Will Have Same Defective Shadow Behaviour Like Before).

**To Reproduce**
1. Open App 
2. Go To Notes Section
3. Create New Note.
4. See Shadow Errors.
5. Create Few More Notes (Up To Next Row).
6. See Previous Row Now Have Normal Shadows And Last Row Will Have Shadow Errors.

**Expected behavior**
Shadows Should Work Normally.

**Screenshots**
![Screenshot_2023-02-11-11-59-58-515_com mhss app mybrain](https://user-images.githubusercontent.com/93785261/218245391-98c3d3e7-6877-44e9-bac3-5cdefb5db352.jpg)
![Screenshot_2023-02-11-12-00-16-462_com mhss app mybrain](https://user-images.githubusercontent.com/93785261/218245395-0bdd78c9-293a-44db-ac52-0d7bb469247f.jpg)
![Screenshot_2023-02-11-12-00-31-205_com mhss app mybrain](https://user-images.githubusercontent.com/93785261/218245397-80452154-05b9-4193-ba9a-a75b98fb0666.jpg)
![Screenshot_2023-02-11-12-00-49-941_com mhss app mybrain](https://user-images.githubusercontent.com/93785261/218245399-8ee95fc5-38d9-4f31-9ed7-90057892ca04.jpg)

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 10, MIUI 12
 - App Version: v1.0.4

**Comment by atikattar1104** [comment]
I Think It Have To Do Something With Layout Size.

**Comment by mhss1** [comment]
Fixed in the latest update
