### ISSUE TITLE
Cannot turn on notifications 

### ISSUE THREAD

**Issue by IvorTollah** [mhss1/MyBrain#143]
Option to allow Notifications is greyed out and cannot be turned on.
![Screenshot_20230308-081437556](https://user-images.githubusercontent.com/56367983/223527591-7f7ddecd-4d22-4e26-a16c-67742fd4c078.jpg)

Using ASUS Zenfone 8 Flip.

**Comment by mhss1** [comment]
It is fixed and will be available in the next update
