### ISSUE TITLE
Calendar Widget Doesn't Recognise Calendar Permission

### ISSUE THREAD

**Issue by IvorTollah** [mhss1/MyBrain#144]
Calendar Widget gives notification that Calendar permissions are required when calendar permission has already been granted. Pressing the refresh button does nothing.

Using Asus Zenfone Flip 8 on Android 13 with Nova Launcher. 
![Screenshot_20230310-102456132](https://user-images.githubusercontent.com/56367983/224164212-b45983f2-8371-48ae-aa96-7014eb2e1af0.jpg)
![Screenshot_20230310-102503015](https://user-images.githubusercontent.com/56367983/224164238-1fb683bd-0282-443a-a586-4f2299272cad.jpg)
![Screenshot_20230310-102508913](https://user-images.githubusercontent.com/56367983/224164247-bd519494-5294-44af-85bd-d2ee5dbcf000.jpg)

**Comment by mhss1** [comment]
Can you remove the widget  and add it again

**Comment by IvorTollah** [comment]
Still having the same problem I'm afraid .

**Comment by mhss1** [comment]
Ok it will be fixed in the next update 👍

**Comment by mhss1** [comment]
Fixed
