### ISSUE TITLE
Support custom Android icon theming

### ISSUE THREAD

**Issue by RustoMCSpit** [mhss1/MyBrain#150]

**Comment by mhss1** [comment]
Added

**Comment by RustoMCSpit** [comment]
> Added

oh sick can you post a new release

**Comment by mhss1** [comment]
it is released now ⚡

**Comment by mhss1** [comment]
what is your device?

**Comment by RustoMCSpit** [comment]
> what is your device?

graphene os, pixel 6

**Comment by mhss1** [comment]
Make sure you enable Themed icons in the "Wallpaper & Style" settings

**Comment by RustoMCSpit** [comment]
> Make sure you enable Themed icons in the "Wallpaper & Style" settings

in settings app? already on

**Comment by mhss1** [comment]
I don't know if Graphene OS has special configurations to be honest. But I've tested it on a Pixel 5, Pixel 6 pro and a Galaxy S21 and it works on all of them.

**Comment by RustoMCSpit** [comment]
> I don't know if Graphene OS has special configurations to be honest. But I've tested it on a Pixel 5, Pixel 6 pro and a Galaxy S21 and it works on all of them.

it doesnt, every other app is fine
