### ISSUE TITLE
Can't export 

### ISSUE THREAD

**Issue by Nahid-S** [mhss1/MyBrain#159]
I can't export says - something went wrong while exporting 

1. Go to settings 
2. Click on export 
3. See error

**Expected behavior**
Export correctly 

**Screenshots**
https://terabox.com/s/1D3Cf-xPHUZEoF_P4fDWWYw

**Smartphone (please complete the following information):**
 - Device: [OnePlus 9r)
 - OS: [e.g. Android 12]
 - App Version [e.g. 1.0.5]

**Comment by mhss1** [comment]
please fill the template and provide more details

**Comment by Nahid-S** [comment]
Sorry about that updated now

**Comment by Uranusek** [comment]
Same problem

**Comment by richarpp** [comment]
Me neither. Same problem

**Comment by droopleshlef** [comment]
I'm not even new to Android development, I haven't even started. But I was able to catch the following. This shows up every time you try to export on master, dev, and even rolling back to acc72b00d809b39e49a849189b95eec3e2afe899. So maybe an API change?

```
Could not instantiate com.mhss.app.mybrain.data.backup.ExportWorker
java.lang.NoSuchMethodException: com.mhss.app.mybrain.data.backup.ExportWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
	at java.lang.Class.getConstructor0(Class.java:2363)
	at java.lang.Class.getDeclaredConstructor(Class.java:2201)
	at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:243)
	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:145)
	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Could not create Worker com.mhss.app.mybrain.data.backup.ExportWorker
```

**Comment by mhss1** [comment]
I'm working on it

**Comment by xorander00** [comment]
Chiming in with my $0.02. I just installed the app and it looks awesome for my use-cases. Only problem is exporting, but in my case the SQLite database doesn't seem to have anything in it.  I was hoping to be able to write a quick py script to render the data out into formats I use on my desktop.
  
Steps:
1. Fresh install.
2. Give it permissions to write to folder (and notifications + calendars).
3. Launch app.
4. Create a dummy task.
5. Export data.
6. Transfer SQLite database to desktop.
7. Open using SQLite Database Manager, which shows the db as having no tables or views.
8. Open using sqlite3 CLI client and execute .tables to confirm that it's not the unlikely event of an issue with the the desktop app.
9. Rinse and repeat a few times to make sure it wasn't circumstantial, but got same result.

I'll look further at this later when I have a chance. Let me know if I missed doing something on my side.

**Comment by mhss1** [comment]
@xorander00 
There is issues currently with the export method used in the app.
I will change it soon to be csv or json or something else
