### ISSUE TITLE
Task widget does not refresh & cant checkout any tasks. Galaxy s21 user.

### ISSUE THREAD

**Issue by n0crey** [mhss1/MyBrain#163]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by mhss1** [comment]
Try removing the widget and add it again.

**Comment by n0crey** [comment]
That worked

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by n0crey** [comment]
Yes it works to remove and add widget. But later again the same issue arrives. Same issue arrive with "remove permissions if app is unused" disabled. I use both task and calender widget, but i got this problem with task. Still galaxy s21 user.
