### ISSUE TITLE
Todo app widget won't update itself

### ISSUE THREAD

**Issue by MansonLuo** [mhss1/MyBrain#168]
**Describe the bug**
1: I press add button in todo app widget, and add todo A, but todo A didn't appear
    in todo app widget
2: after I add todo app widget in home screen, I open app, create a todo A, todo A 
    didn't appear in todo app widget after I return to home scree which todo app widget 
    live.

**Comment by mhss1** [comment]
Make sure you have the latest version (v1.0.6) and try removing the widget and adding it again.

**Comment by MansonLuo** [comment]
yes， I'm using latest version (1.0.6), removing and readd can update newest data again,but 
still don't fix the problem.
by the way, i eun it in android 10

**Comment by MansonLuo** [comment]
it still can't update itself after reading

**Comment by MansonLuo** [comment]
I see several same questions in closed issues, is it difficult to fix that?

**Comment by mhss1** [comment]
I tested it on 2 devices with Android 13 and 8 and it works fine.
I will test it on more devices to find the problem.

**Comment by MansonLuo** [comment]
thanks， buddy
