### ISSUE TITLE
Bug in export function

### ISSUE THREAD

**Issue by sinan-q** [mhss1/MyBrain#172]
**Describe the bug**
While exporting, it appears that the entire diary is not being exported. In my case, the last two diary entries are not getting exported. I confirmed this by reading the exported SQLite file using a third-party app, and it's evident that the last two diary entries do not exist there.
**To Reproduce**
1. Create a diary entry
2. Export
3. Import
4. The newly created diary is missing

**Expected behavior**
All diary entries should be exported while exporting

**Screenshots**
Uploaded a video showing the issue.
https://github.com/mhss1/MyBrain/assets/87349745/b15c4eef-e200-4855-ad93-23b9a5a44661

**Smartphone (please complete the following information):**
 - Device: Poco M2 Pro
 - OS: Android 12
 - App Version: 1.0.6(7)

**Additional context**
Import functionality is working as expected.

**Comment by mhss1** [comment]
I noticed this problem also in other spaces. I will work on changing the method of exporting data to be more reliable.

**Comment by Uranusek** [comment]
I lost some tasks and notes because of this bug :/ When can we expect it to be fixed?

**Comment by mhss1** [comment]
@Uranusek Sorry about that. This will be fixed very soon.

**Comment by mhss1** [comment]
Fixed
