### ISSUE TITLE
Widgets not updating

### ISSUE THREAD

**Issue by GaspardCulis** [mhss1/MyBrain#173]
**Describe the bug**
The Calendar and especially the Todos widgets do not update after adding a new task unless the widget gets removed and the re-added

**To Reproduce**
1. Add the Todos widgets to your home screen
2. Add a new task
3. The newly created task isn't shown in the widget

**Expected behavior**
The widget should update to display the new task

**Smartphone (please complete the following information):**
 - Device: Pixel 5a barbet
 - OS: Lineageos 20-20230902-microG-barbet
 - App Version: 1.0.6

**Additional context**
May be caused by my custom ROM

**Comment by Rafee-M** [comment]
I made a issue regarding this too. After a restart it became fine. But after a while I noticed the same issue again.

OS: OxygenOS 13

**Comment by zauberervonOZ** [comment]
Same for me, also on LOS 20 w/ microG, wish i could properly use this beautiful app :(

**Comment by mhss1** [comment]
It should be fixed now after I upgraded the Jetpack Glance library version. If you still see the same problem after the next release, it most probably your phone's os
