### ISSUE TITLE
Subtasks feature does not appear to work

### ISSUE THREAD

**Issue by hugo1984fr** [mhss1/MyBrain#174]
**Describe the bug**
I can add a sub-task but there is no way to name them; only check-boxes can be created.

**To Reproduce**
1. create a Task
2. Click on Add sub task
3. Try to enter text to label the subtask

**Expected behavior**
Ability to name the subtask

**Smartphone (please complete the following information):**
 - Device: Moto Z3 Play
 - OS: LineageOS v20
 - App Version - current

**Comment by mhss1** [comment]
fixed
