### ISSUE TITLE
import does not work

### ISSUE THREAD

**Issue by LeOS-GSI** [mhss1/MyBrain#178]
**Describe the bug**
I have exported data on one device. It includes diary, bookmarks and tasks. Then I have shared the data file to second device. On 2nd device I have used import data, but no data imported. No error message.
Same happens wehen using ex and import on same device

**To Reproduce**
1. Go to '.Export Data'
2. Click on 'export data'
3. Click on ' import data'
4. Check data import in notes or diary ir bookmarks or task

**Expected behavior**
All data should be visible

**Screenshots**
./.

**Smartphone (please complete the following information):**
 - Device: MiMax3, Redmi note 10, Mi Pad5
 - OS: LeOS GSI - Android 14
 - latest

**Additional context**
./.

**Comment by mhss1** [comment]
Similar issue already exists

**Comment by LeOS-GSI** [comment]
> Similar issue already exists

I have searched the whole issues, but there is none for import issues. For export I can find a issue, but not for import.

**Comment by mhss1** [comment]
Yes, I know but the problem with the export is causing the problems in import as well.
It will be fixed soon.
