### ISSUE TITLE
Issue with diary 

### ISSUE THREAD

**Issue by Jaik72** [mhss1/MyBrain#181]
**Describe the bug**
The diary page takes the title but nothing can be entered in description area.

**To Reproduce**
1. Go to 'Diary
2. Click on Title and enter name
3. Scroll down to Description 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S22]
 - OS: [e.g. Android 13]
 - App Version [e.g. 1.2]

**Additional context**

**Comment by mhss1** [comment]
You have to disable reading mode first

**Comment by Jaik72** [comment]
Thank you very much. That solved the problem.
