### ISSUE TITLE
MyBrain clone on Play Store

### ISSUE THREAD

**Issue by ch3thanhs** [mhss1/MyBrain#188]
I found a clone of this app on the Play Store - https://play.google.com/store/apps/details?id=work.mywild.mybrain

The developer's apps are all just clones of other open-source projects with AI generated app icons.

The developer's GitHub - https://github.com/djacidfx

**Comment by ngocanhtve** [comment]
> The developer's GitHub - https://github.com/djacidfx

His fork: https://github.com/djacidfx/Task-Maestro

He just forked My Brain and then re-released it on Google Play with a different name and different icon.

**Comment by ch3thanhs** [comment]
So, the developer's account seems to be suspended. I'll close this issue.
