### ISSUE TITLE
Diary not compatible with increased display settings 

### ISSUE THREAD

**Issue by didi8517** [mhss1/MyBrain#205]
**Describe the bug**
This only happens in diary mode. When adding an entry, the content field disappears under the keyboard and I have to set it to floating in order to see what I'm typing. This is due to increased display mode in system wide settings, affecting all fonts etc.
 
**To Reproduce**
1. Go to 'Diary'
2. Click on '+' button
3. Click on content field

**Expected behavior**
A clear and concise description of what you expected to happen

Just as in the other modes I would expect the whole window to scroll down so as to make the content field with text visible above the keyboard - and the possibility to just scroll down to get back to e.g. title field etc.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG Velvet
 - OS: Android 12
 - App Version 1.0.7

**Additional context**

It may have to do with the language (German) which unfortunately I cannot change in the settings, in order to see if that changes anything. Because, as you can see in the screenshot the last mood option doesn't really fit and the text is shown vertically... It does have to do with my general system settings for screen/font size being bigger than just the standard factory setting. When I changed it back to normal it behaved as expected. So it has to do with the last mood description not fitting in and ending up taking up more space etc... 
This means there is a certain solution, but it also means this app is not compatible with certain system wide settings for people like me who prefer an increased display for better readability. This is in the standard display settings, not one of the accessibility settings.
![Screenshot_20240519-175805](https://github.com/mhss1/MyBrain/assets/115153021/056aaa98-51f3-4ac3-b13b-bcb097df0d1d)

**Comment by didi8517** [comment]
This is how it looks if I change the setting to normal

![Screenshot_20240519-183647](https://github.com/mhss1/MyBrain/assets/115153021/167ab292-c187-4164-91b0-6197ac407e38)

**Comment by didi8517** [comment]
I just checked the setting is called "display_density_forced". In the system settings you have normal and two bigger ones, I had the first which corresponds to a value of 480 (as opposed to nothing as standard setting) - the max is 540.

**Comment by mhss1** [comment]
Fixed
