### ISSUE TITLE
The app won't open any note after the latest update, crashes. 

### ISSUE THREAD

**Issue by Leeleevy** [mhss1/MyBrain#209]
**Describe the bug**
After the latest update to the version 1.0.7. the app started crashing when clicking on a note. It doesn't behave this way with the diary entries, tasks or bookmarks, only notes. 

**To Reproduce**
1. Go to 'notes'
2. Click on 'any note'
4. See the home screen of your phone instead. 

**Expected behavior**
I expected the notes to still be openable and editable. 

**Smartphone (please complete the following information):**
 - Device: [Redmi 10C]
 - OS: [Android 13 TKQ1.221114.001]
 - App Version [1.0.7]

**Additional context**
A detail that might or might not be important is, I got a new device, for my older one this new version of the app wasn't available on F-droid so I kept using v.1.0.4 there. When I wanted to install MyBrain on the new device the disclaimer said I won't be able to import the data from the older versions into it, so I proceeded to first install the v.1.0.4, import my data from the old device there, and then update the app through F-droid to the v.1.0.7. That's when I found out the notes don't open anymore.

**Comment by mhss1** [comment]
If you are Grid view can you change it to List view and check if it works

**Comment by Leeleevy** [comment]
> If you are using Grid view can you change it to List view and check if it works

Thank you. Yes it has indeed worked (both viewing and editing). It didn't occur to me the problem might be with the grid view. So you can rename the issue now.

**Comment by mhss1** [comment]
This problem has been already fixed for the next release
