### ISSUE TITLE
assistant bug

### ISSUE THREAD

**Issue by Pacidus** [mhss1/MyBrain#219]
**Describe the bug**
When asked to the assistant to add an event to the calendar,
The assistant summarise perfectly the task asked but the calendar is not updated

**To Reproduce**
1. API https://api.groq.com/openai/v1, model llama3-8b-8192
2. Go on assistant 
3. Ask for adding an event to the calendar 
4. Exit and open the calendar 
5. Nothing 

**Expected behavior**
The calendar should be updated

**Smartphone (please complete the following information):**
 - Device: Redmi note 10 pro 
 - OS: Android 13, miui 14
 - App Version 2.0.0

**Comment by mhss1** [comment]
Assistant only gives you information from your prompts but can't perform actions such as adding an event.

**Comment by Pacidus** [comment]
Oh sorry 😂
