### ISSUE TITLE
Diary: text disappears under KB and no save/warning on back

### ISSUE THREAD

**Issue by didi8517** [mhss1/MyBrain#229]
**Describe the bug**
As described in this issue: https://github.com/mhss1/MyBrain/issues the same continues with the diary: the text disappears under the keyboard. Ironically in portrait mode this is not the issue, there the text window gets resized to fit.
Furthermore: if you hit the back button, unlike in the notes, your entrance is lost, it will not be saved. It is strange to not have the same behaviour throughout the app, as you would expect and it's frustrating to have typed in something and lose it all ... Either have the same, or at least show a message asking if to save or not...

**To Reproduce**
for bug 1 see other issue.
For bug 2 type in anything in diary, then hit back button all is irreversibly lost.

**Expected behavior**
for bug 1 see issue linked.
For bug 2: either as in notes that it will be saved automatically, else a confirmation asking whether to save entry or not.

**Smartphone (please complete the following information):**
 - Device: LG Velvet (LM-G910)
 - OS: Android 12
 - App Version: 2.0.0

Thanks

**Comment by didi8517** [comment]
I just so happened to realize that in another issue I posted in the screen shot you can see that the text field (including the save button) didn't disappear under the keyboard as it now does. 
https://github.com/mhss1/MyBrain/issues/205#issuecomment-2119295128
Also I just realised that the issue that then had been fixed seems to be partially back. I do not have an increased density as back then, but the last of the moods is again not fully visible, albeit in a different way also than back then when I posted the other issue

**Comment by mhss1** [comment]
The mood options are not scrollable for you?

**Comment by didi8517** [comment]
Yes they are, I didn't know that, had never thought of it! Good to know.

**Comment by didi8517** [comment]
Sorry, Just realised another "funny" thing. When editing an existing note, it will also disappear under the keyboard, but there is no save button and backing out it will be saved automatically, not lost as when writing a new note.

**Comment by mhss1** [comment]
fixed
