### ISSUE TITLE
Can't assign proper time to task.

### ISSUE THREAD

**Issue by nbuhrke1** [mhss1/MyBrain#230]
**Describe the bug**
When I try to create a new task and select "due date" the digital clock portion doesn't correctly display. It is incorrectly sized and centered, and doesn't apply the correct time from the analog portion.

Additionally, it forces the time of the due date to be the same as the current time.

**To Reproduce**
1. Go to Tasks
2. Click on Blue Plus
3. Click on "Due Date" checkbox 
4. Select date
5. Press blue okay button 
6. See error where the digital clock portion normally should be.
7. Error continues after setting time with the due date always set to current hour/minute.

**Expected behavior**
Normally, I'd expect to see the time that the analog clock is pointing at displayed on the digital portion. 

It would then also set the due date of the task to the correct hour/minute.

**Screenshots**

![Screenshot_20240915-062933_My Brain.jpg](https://github.com/user-attachments/assets/8553239d-fc71-4de6-bbf8-e18b2bdb8691)

![Screenshot_20240915-062941_My Brain.jpg](https://github.com/user-attachments/assets/ff7d20e0-9139-48ed-80bb-4cb322a2bdb3)

**Smartphone (please complete the following information):**
 - Device: Galaxy A31
 - OS: Android 12
 - App Version 2.0.0

**Comment by mhss1** [comment]
Fixed
