### ISSUE TITLE
Rotating phone when editing a previously made note will cause you to lose newly written text. 

### ISSUE THREAD

**Issue by JamesDean3** [mhss1/MyBrain#231]
**Describe the bug**
Rotating phone when editing a previously made note will cause you to lose newly written text. 

**To Reproduce**
1. Go to a previously written note.
2. write something new in the note.
3. collapse/close the keyboard
4. Rotate phone
5. You will see that it removes this from the edit mode and no longer has the newly added text. 

This can be a problem when you need to go to another app to look up something real fast with the intent to add information to your note, only to have your phone rotate the screen for whatever reason, then find that you lost whatever you wrote.

**Expected behavior**
Have it save as you write.

**Smartphone (please complete the following information):**
 - Device: Pixel 6 Pro
 - OS: Android 14
 - App Version: 2.0.1

**Comment by Maxitendo1** [comment]
I also have this issue. Please fix. @mhss1

**Comment by mhss1** [comment]
Fixed
