### ISSUE TITLE
Numbers cut off in time picker UI

### ISSUE THREAD

**Issue by fernbread** [mhss1/MyBrain#232]
**Describe the bug**
The numbers are cut off in the time picker UI.

**To Reproduce**
1. Create a task
2. Set a due time

**Expected behavior**
The time in the time picker should be fully visible.

**Screenshots**

<details><summary><img src="https://github.com/user-attachments/assets/fc9c0d8f-6a0c-45de-b204-bd8e986afd94" width=200 /></summary>

![image](https://github.com/user-attachments/assets/fc9c0d8f-6a0c-45de-b204-bd8e986afd94)

</details>

**Smartphone (please complete the following information):**
 - Device: Pixel 8 Pro
 - OS: Android 14
 - App Version: 2.0.1 (versionCode 10) installed from F-Droid

**Comment by mhss1** [comment]
This issue has been fixed

**Comment by fernbread** [comment]
Which version contains the fix? For me it is currently broken in 2.0.1

**Comment by mhss1** [comment]
It will be available in the next version
