### ISSUE TITLE
Essayish Request add the guided meditation videos from UCSD

### ISSUE THREAD

**Issue by justinPemberton** [mhss1/MyBrain#243]
The University of California in San Diego runs a open program that has a bunch of guided meditations I believe that this would be a great addition

**Comment by justinPemberton** [comment]
https://cih.ucsd.edu/mindfulness/guided-audio-video
I think the layout that these videos are already in is pretty good if you were to just copy this over to the.
Honestly, I think this is a pretty good request for someone wanting to get involved with the project. So, let me try and get involved

**Comment by mhss1** [comment]
Thank you for the suggestion! While I appreciate the idea, this isn't something I plan to add right now and doesn't align with the direction I have for the app. My focus is currently on other areas.
Thank you again for your understanding and support.
