### ISSUE TITLE
Sunday is missing in the diary

### ISSUE THREAD

**Issue by MisterLights** [mhss1/MyBrain#244]
Hey !

Since about a week I noticed that there is one day missing per week in the diary calendar. I would like to keep my data so I'm scared to uninstall and reinstall.

 - Device: Oppo Find X3 Neo
 - OS: Android 13
 - App Version: 2.0.2

**Additional context**

![Screenshot_2024-10-19-12-04-10-56_9e194f7f34ef1daa83c2dc6a9797f75b](https://github.com/user-attachments/assets/07de7126-6606-40e4-a7c6-fc281295d725)
![Screenshot_2024-10-19-12-04-13-29_9e194f7f34ef1daa83c2dc6a9797f75b](https://github.com/user-attachments/assets/86cc84f6-8106-4494-a0eb-19088ad60707)

**Comment by mhss1** [comment]
Hi, sorry for this bug. The issue has been fixed and will be included in the next release.

**Comment by MisterLights** [comment]
Oh cool thanks !
