### ISSUE TITLE
Only 6 days of the week on journal entry calendar

### ISSUE THREAD

**Issue by rfbio** [mhss1/MyBrain#246]
When adding a new journal entry the calendar menu only has 6 days listed; a whole column of dates are missing.

Chose **My Brain** > **Diary** > "**+**" > "[current date]" (to chose an alternate date NOT today)

 - Device: Galaxy A53 5G UW
 - OS: Android 14
 - App Version 2.0.3

![Screenshot_20241028_133456_My Brain](https://github.com/user-attachments/assets/839f70ca-50b5-4b05-8341-33c8c70d0e75)

**Comment by mhss1** [comment]
This issue is already fixed and will be available in the next release.

**Comment by rfbio** [comment]
Awesome! Thank you so much.

**Comment by MisterLights** [comment]
Hey! I know the issue has been fixed and will be release in the next patch but would you know when it will be available? 

I've been missing out on my sundays in my diary for +1month :'(

Thank you.

**Comment by mhss1** [comment]
@MisterLights Hey, sorry for that. I was waiting for something else to be added with it in the release. I will skip it for now and publish the release today.
