### ISSUE TITLE
Request Login and Backup feature

### ISSUE THREAD

**Issue by AbiXnash** [mhss1/MyBrain#250]
I'm frustrated when I need to manually back up my data or log in with separate accounts, as it can be time-consuming and leads to a fragmented experience across devices.

I would like to have a Google login feature, allowing users to log in quickly with their Google account, which enhances convenience and accessibility. Additionally, a backup feature that syncs data to Google Drive would ensure data security and easy recovery, even across different devices.

This feature would be particularly useful for users who frequently switch devices or need a reliable backup solution.

**Comment by mhss1** [comment]
Thank you for the suggestion. Similar issue already exists.
