### ISSUE TITLE
No scrolling, cursor disappears under keyboard (notes and diary)

### ISSUE THREAD

**Issue by deADvErv** [mhss1/MyBrain#29]
When typing, once the cursor reaches the keyboard height, it disappears under the keyboard instead of scrolling the page down.

**To Reproduce**

1. Open Notes or Diary
2. Start typing in Content box
3. Keep typing until cursor reaches keyboard height
4. It is no longer possible to see what you type

**Expected behavior**
I expected the content box to scroll down as the cursor goes to the next line.

**Screenshots**
![Screenshot_20220605-204730_My Brain](https://user-images.githubusercontent.com/106920508/172057702-9b161e38-db1d-426d-b788-455b7885dc44.jpg)
![Screenshot_20220605-204737_My Brain](https://user-images.githubusercontent.com/106920508/172057707-8e7b1320-fa14-426a-9ca6-9a3fbd243c13.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy F62
 - OS: Android 12
 - App Version 1.0

**Comment by mhss1** [comment]
Fixed
