### ISSUE TITLE
Add online sync and back up

### ISSUE THREAD

**Issue by LanoyeRamia** [mhss1/MyBrain#31]
**Is your feature request related to a problem? Please describe.**

The user interface is great so I'd love to use this as main but it's basically useless to me because I want to be able to access my notes anywhere and anytime especially if my phone broke or loss. I want to save it for future use and make sure I get to read it in the future. 

**Describe the solution you'd like**

Use email for sign in and backup purposes. Ofc with privacy.

**Comment by mhss1** [comment]
Similar Issue already exists
