### ISSUE TITLE
Hard to read Calendar details in widget

### ISSUE THREAD

**Issue by GammaSQ** [mhss1/MyBrain#45]
Calendar widget presents event details in hard to read font-color

**To Reproduce**
1. set some calendar event with title and details (I have mostly locations, but descriptions show the same behaviour)
2. Add a MyBrain calendar widget to the homescreen
3. The title of the event is white on dark, clearly visible. Description is black on dark, hard to make out.

[I'm using Lawnchair launcher in case that matters.]

**Expected behavior**
Font-Color of widget is either fixed to a sensible value (white) or, if at all theme-dependent, the setting is made clear.

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 11
 - App Version 1.0.1 (f-droid)

**Comment by WolfgangSchiller1986** [comment]
Make widget transparent, while you're at it. Please.
