### ISSUE TITLE
backspace behavior

### ISSUE THREAD

**Issue by bdmartin94** [mhss1/MyBrain#48]
**Describe the bug**
When holding the backspace button, only one character is erased at a time. To erase more than one character you have to repeatedly tap the button. 

**To Reproduce**
1. Go to Notes and open or create a note.
2. Enter an amount of text longer than one character.
3. Press and hold backspace button to erase everything. 
4. Only one character/space will erase unless you tap repeatedly.

**Expected behavior**
When holding the backspace button, after a brief moment it should start to rapidly erase text until the button is released. 

**Screenshots**
Not able to demonstrate with static image. 

**Smartphone (please complete the following information):**
 - Device: Galaxy S8+
 - OS: Android 9
 - App Version 1.0.1

**Additional context**
"Hold to erase" is standard behavior on most apps, except in certain cases, e.g. occasionally in a text field such as password entry.

**Comment by mhss1** [comment]
it might be a problem with your keyboard/device . I tested it on multiple devices but it works fine.
