### ISSUE TITLE
Calendar event creation screen

### ISSUE THREAD

**Issue by ItamiWasTaken** [mhss1/MyBrain#5]
**Is your feature request related to a problem? Please describe.**

When there is no additional calendar app installed, you cannot add events.

I currently have an additional calendar app, but it'd be nice to have a consistent UI. (the main app and the calendar event screen)

**Describe the solution you'd like**

I'm not a developer and I respect devs who work on wonderful apps. that aside, I think adding the ability to add calendar events would be both functional and keep the UI consistent.

**Additional context**

**Comment by mhss1** [comment]
Thank you for the suggestion👍. I thought about this as well and it is one of the top priorities that will be added soon.
