### ISSUE TITLE
Zero knowledge Encryption 

### ISSUE THREAD

**Issue by shubhamsoni-2699** [mhss1/MyBrain#53]
**Is your feature request related to a problem? Please describe.**
Your product should contain some safety features for end users.

**Describe the solution you'd like**
With a zero knowledge Encryption the product is more reliable for users.

**Additional context**

**Comment by mhss1** [comment]
The app does not have internet permission. All the data is stored on your device. Zero knowledge encryption will be implemented if in the future a feature that requires data leaving the device like cloud sync for instance is added.
