### ISSUE TITLE
Repeated events created before installation don't show in calendar

### ISSUE THREAD

**Issue by vedgar** [mhss1/MyBrain#54]
**Describe the bug**
If a repeating event is made before first accessing calendar in the app, its instances will not be shown. 

**To Reproduce**
1. Make an event with daily frequency 
2. Next day install the app
3. Go to calendar
4. See the event is not there

**Expected behavior**
To see the instances of repeating events. 

**Smartphone (please complete the following information):**
 - Device: Huawei Mediapad M5
 - OS: Android 8.0.0
 - App Version 1.0.1

**Comment by mhss1** [comment]
Fixed
