### ISSUE TITLE
Text overflow in Dashboard labels in Polish translation

### ISSUE THREAD

**Issue by maciej-klupp** [mhss1/MyBrain#60]
### Description of the problem
I am translating the app to Polish, however the translated labels for the summaries in the dashboard are too long and overflow to the next line. I suggest that the text is made smaller in such instances, allowing each word to fit in a single line.
### Screenshot
![obraz](https://user-images.githubusercontent.com/100523238/186952667-2de4776b-33d1-4941-a65a-f1aaa11d3ff0.png)

**Comment by mhss1** [comment]
Thank you for your contribution. when you finish, just submit a pr and I will decrease the size a little bit in the next update.
