### ISSUE TITLE
Markdown Reader view turns into editing with just a tap

### ISSUE THREAD

**Issue by fossimprove** [mhss1/MyBrain#68]
**Describe the bug**
When reading notes in markdown preview, with just a small single tap it turns into Editing mode, which is annoying. Also the scrolling in markdown preview is not smooth as scrolling while editing.

**To Reproduce**
1. Go to 'Notes > Any note to read'
2. Single tap on any space
3. Turns into editing mode

**Expected behavior**
Its better to have a locked button to enter into editing mode. We can only go to editing mode by clicking on that button. 

Additionally, Under markdown preview, show tab of info on created & edited date and words count. 
Plus, Make scrolling smooth in preview (like in editing)
Thus helps us to read markdown preview.

 - OS:  Android 12

Hey Dev, good to see some commit recently. I was worried, looking at no commit for several weeks.

Glad you are back. Cheers ;)

Hope those 3 point are clear.
1. Only button to enter editing
2. Info tab on note (date+word count)
3. Smooth scroll for preview

For 1 and 3 you may check Quillnote (app), which does it very well.

**Comment by mhss1** [comment]
Thank you for reporting. I actually intended to do this so you can start writing immediately. It's not a bug. I get your point. It actually makes sense to use only the button.

**Comment by atikattar1104** [comment]
Fun Fact :- I Have Also Mentioned The Same Suggesion In #88
