### ISSUE TITLE
Add support for blocking screenshots from being taken

### ISSUE THREAD

**Issue by grrrrr** [mhss1/MyBrain#71]
I am aware that this is not a perfect privacy solution and there are ways around it but it would be useful to have `MyBrain` block the ability to take screenshots.

While the risks / concerns of someone remotely taking a screenshot of `MyBrain` on most peoples devices phone are low there are still users who may be more high risk, it is a possibility that some malware is setup to take screenshots of the recorded dataand could result in issues in restrictive countries

Additionally with screenshots blocked, switching apps would result in you seeing `MyBrain` is your list of open apps but not seeing the screen it's contents, an extra benefit

My suggestion would be to add a toggle allowing users to opt-in to this feature,.

Some apps that do that have this option if examples/comparison is needed

* KeepassDX (always blocked)
* Signal (allows toggling screenshot capture on or off)
* ProtonMail (allows toggling screenshot capture on or off)
* Aegis (allows toggling screenshot capture on or off)
* MediLog (allows toggling screenshot capture on or off)
* RedReader (allows toggling screenshot capture on or off)

**Comment by atikattar1104** [comment]
I Use This Code For Blocking Screenshots In My Apps. :- 
> getWindow().setFlags(WindowManager.LayoutParams.FLAG_SECURE, WindowManager.LayoutParams.FLAG_SECURE);

I Put These Line In `onCreate()`. Android Itself Tells In Toast That `This App Doesn't Allow Screenshots`. Even When Screen Recording, Screen Is Recorded Black In Colour. But Actually, The Content Is Visible To User.

Hope This Will Help.
Thanks!
