### ISSUE TITLE
Changes disappear when screen is rotated

### ISSUE THREAD

**Issue by Lolozweipunktnull** [mhss1/MyBrain#73]
**Describe the bug**
If you edit a diary entry and rotate the screen, the changes disappear again. 

**To Reproduce**
1. Create a new diary entry and write something.
2. Save.
3. Open again und write something additional.
4. Flip the phone/screen.
5. Changes disappear.

**Expected behavior**
What has already been written should stay there.

**Smartphone:**
 - Device: Asus Zenfone 7 
 - OS: Android 12
 - App Version: 1.0.1

Edit: Its the same with notes.

**Comment by mhss1** [comment]
Fixed
