### ISSUE TITLE
When i switched app mode to light  while device mode dark , the texts don't appear, text color still white

### ISSUE THREAD

**Issue by bindars** [mhss1/MyBrain#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy S22]
 - OS: [e.g. Android 13]
 - App Version [e.g. 1.2]

**Additional context**

**Comment by mhss1** [comment]
Can you please add more details mentioned in the template

**Comment by mhss1** [comment]
Closed the issue for no details about it
