### ISSUE TITLE
Update app in f-droid and update features

### ISSUE THREAD

**Issue by winterwolf45** [mhss1/MyBrain#76]
Hi thank you for create this software
 I'm so sorry can I ask why didn't you  update it in f-droid?
And can I ask why don't  you add features
I'm trying introduced your software to  my friends but when they are see you do not add features, many of which are very useful  They will regret installing your app , but all always they are telling I wish developer mybrain add it feature
Again thank your for create this best and so beautiful software.

**Comment by mhss1** [comment]
F-Droid  should update to the next version automatically. I don't know why it took very long time this update. I'll try to fix this issue ASAP.

**Comment by mhss1** [comment]
Regarding the features I will add more features in the future. Thank you for sharing the app for your friends 😊
