### ISSUE TITLE
Tasks widget not updating when adding new tasks from app

### ISSUE THREAD

**Issue by Terkyz** [mhss1/MyBrain#8]
**Describe the bug**
Tasks widget not updating when adding new tasks

**To Reproduce**
1. Create a task widget
2. Open the app and create a new task
3. Check the widget again

**Smartphone (please complete the following information):**
 - Device: [Galaxy A10]
 - OS: [e.g. Android 11]
 - App Version [1.0]

Additional note: After being inside My Brain for a while the widget updated, but it wasn't instantly.

**Comment by mhss1** [comment]
I'll optimize it more 👍. But this issues might be because the library used for widgets (Compose Glance) is still in alpha.
