### ISSUE TITLE
Brazilian Portuguese Interface Translation

### ISSUE THREAD

**Issue by abChimp** [mhss1/MyBrain#81]
**Is your feature request related to a problem? Please describe.**
There is no Brazilian Portuguese translation.

**Describe the solution you'd like**
I would do the work of translating the app. But I need to know your guidelines.

**Additional context**
Keep It Simple And Stupid because I am new to git.

**Comment by mhss1** [comment]
After you fork the project:
- Create a new directory in : [app/src/main/res](https://github.com/mhss1/MyBrain/tree/master/app/src/main/res) called "values-pt-rBR"
- in this directory create a new file called strings.xml
- copy the contents of [app/src/main/res/values/strings.xml](https://github.com/mhss1/MyBrain/blob/master/app/src/main/res/values/strings.xml) file
- replace the English words with the right translation (replace the text between the "> <" and not the text between the qoutes.)

**Comment by abChimp** [comment]
I forked the project and commited my translation to [app/src/main/res/values-pt-BR/strings.xml](https://github.com/abChimp/MyBrain/blob/master/app/src/main/res/values-pt-BR/strings.xml).
Now, what is the next step? A PR or waiting for a review of the strings?
