### ISSUE TITLE
Widget not syncing properly

### ISSUE THREAD

**Issue by Leetcodr** [mhss1/MyBrain#82]
**Describe the bug**
After creating new task and closing app, widget does not show newly created task 

**To Reproduce**
1. Create 'tasks' widget
2. Open app by tapping on 'tasks' on widget
3. Create a new task
4. Exit app
5. Check widget for new task

**Expected behavior**
Newly created task should be visible on widget after exiting the app

**additional context**
When we open app from its icon and create a new task then it works as expected but when we open app by tapping on 'tasks' written on widget then add task and close app then widget is not synced i.e. new task is not showing on the widget

**Comment by tranlequanghung52** [comment]
I also see this bug, but sometimes it does update properly

**Comment by mhss1** [comment]
@tranlequanghung52 @Leetcodr Are you sure that you have the latest version? I tested it on multiple devices and it works without problems.

**Comment by Leetcodr** [comment]
I'm using latest version 1.0.2 from fdroid on my device realme gt neo running A12 RUi 3.0. Given steps to reproduce bug are correct but bug is not reliably produced everytime while using the app only sometimes(maybe battery optimization is to blame) Nice app otherwise

**Comment by mhss1** [comment]
@Leetcodr Thanks for the feedback 👍
