### ISSUE TITLE
[Bug] Font Changes When Marking Sub Tasks As Complete

### ISSUE THREAD

**Issue by atikattar1104** [mhss1/MyBrain#87]
v1.0.2 . When Marking A Sub Task As Complete, After Changing The App Font To Something Else From Settings, The Changed Font Changes Again Back To Default Only Of The Sub Task. Fonts Of Other Text Remains Unchanged.

**Smartphone (please complete the following information):**
 - Device: Redmi 7A
 - OS: Android 10, MIUI 12
 - App Version: v1.0.2

**Comment by mhss1** [comment]
You mean that only the font of the subtasks returns to default?
