### ISSUE TITLE
[Feature Request] Viewing Mode For Tasks, Notes, And Other Stuff.

### ISSUE THREAD

**Issue by atikattar1104** [mhss1/MyBrain#88]
**Is your feature request related to a problem? Please describe.**
Tasks, Notes, Bookmarks, Etc. Opens In Editing Mode Rather Than Viewing Mode, Causing Accidental Erasure Of Text.

**Describe the solution you'd like**
2 Seperate Modes. 1st, For Viewing Stuff (Default View), And 2nd, Edit Button For Editing The Data.

**Comment by mhss1** [comment]
This feature already exists for notes and will be implemented for more spaces
