### ISSUE TITLE
Calendar crash

### ISSUE THREAD

**Issue by toshi2d** [mhss1/MyBrain#97]
**Describe the bug**
Calendar crash everytime, when trying to edit info in already created event

**To Reproduce**
1. Go to calendar
2. Create event and save it
3. Open even and edit it, then save it

**Expected behavior**
Calendar saves edited event

**Smartphone (please complete the following information):**
 - Device: Nothing phone (1)
 - OS: Android 12
 - App Version: 1.0.3

**Comment by SteveMutter** [comment]
Bug Confirmed on VollaPhone

To Reproduce
Steps to reproduce the behavior:

    Go to calendar
    Create event and save it
    Open even and edit it, then save it
    See error

Expected behavior
Calendar saves edited event

Smartphone (please complete the following information):

    Device: VollaPhone
    OS: VollaOS Based on Android 11 https://volla.online
    App Version: 1.0.3

**Comment by mhss1** [comment]
Fixed
